-- Deliberately empty.
--
-- The policy migrations before this one were hand-authored, so no drizzle
-- snapshot was written alongside them. drizzle-kit compares the schema against
-- the newest snapshot, which still described the database as it was before any
-- of them, and so proposed creating every policy table again. On a database
-- that has run those migrations that proposal fails on the first statement.
--
-- This file carries no statements. It exists so the snapshot beside it becomes
-- the newest one and describes the schema as it actually is, which is what
-- makes the drift check meaningful again rather than permanently red.
